import VideoList from "@/components/Videolist";
import VideoPlayer from "@/components/Videoplayer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Homepage - Playgonal",
  description: "Generated by create next app",
};

const Home:React.FC = async () => {
  const res = await fetch(process.env.REACT_APP_ENDPOINT+'data/page1.json');
  const json = await res.json();
  const data = json.page["content-items"].content
  return (
    <div className="main-container">
      <VideoPlayer title="The Guardians Of Galaxy" src="/video/video.mov"/>
      <VideoList data={data.slice(0,3)} title="Comedy Movies" />
      <VideoList data={data.slice(3,6)} title="Romantic Movies" />
      <VideoList data={data.slice(6,9)} title="Action Movies" />
    </div>
  
  );
}

export default Home